version: "3.3"
services:
    node:
        build:
            context: docker
            dockerfile: development/node/Dockerfile
        volumes:
            - ./:/app
        user:
            "1000:1000"
