version: "3.3"
services:
    node:
        build:
            context: docker
            dockerfile: node/Dockerfile
        volumes:
            - ./:/app
        user:
            "1000:1000"
    node-server:
        build:
            context: docker
            dockerfile: node/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        command:
            - "npm"
            - "run"
            - "start"
    json-server:
        build:
            context: docker
            dockerfile: json-server/Dockerfile
        volumes:
            - ./docker/json-server:/app
        ports:
            - "3001:3001"
